# Generated by Django 5.0 on 2024-06-21 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_is_profile_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_profile_complete',
        ),
    ]
